### ISSUE TITLE
Similar concepts

### ISSUE THREAD

**Issue by Zayelion** [YGOProTH/ygopro-core-windows#1]
https://github.com/SalvationDevelopment/YGOPro-Library-Builder

**Comment by ekaomk** [comment]
ignore it, i created this for some reason.

**Comment by Zayelion** [comment]
https://github.com/Fluorohydride/ygopro/issues/1628 come join us.

**Comment by ekaomk** [comment]
My git skill and English very bad. I may broke your team and make me shame. I do not want to insult myself but that true.

**Comment by Zayelion** [comment]
It will be ok I promise. Its best to speak in your native language and translate when you feel the need. We are collecting information so everyones experience is needed.
